config/routes.rb
Rails.application.routes.draw do

  root 'home#index'
  resources :tv
  resources :movies
  resources :people
  resources :search
  resources :genres
  devise_for :users, :controllers => { registrations: 'registrations' }
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/genres_controller.rb
class GenresController < ApplicationController
  def index
    @moviegenres = Tmdb::Genre.movie_list
  end

  def show
    @moviegenre = Tmdb::Genre.movies(params[:id], page: params[:page])
    @moviegenres = Tmdb::Genre.movie_list
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/movie_controller.rb
class MovieController < ApplicationController
  def index
    @movies= Tmdb::Movie.popular(page: params[:page])
    @image = "https://image.tmdb.org/t/p/w500"

  end

  def show
    @movie = Tmdb::Movie.detail(params[:id])
    @image = "https://image.tmdb.org/t/p/w500"
  end
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  def index
    @movies= Tmdb::Movie.popular(page: params[:page])
    @image = "https://image.tmdb.org/t/p/w500"

  end

  def show
    @movie = Tmdb::Movie.detail(params[:id])
    @image = "https://image.tmdb.org/t/p/w500"
  end
end

app/controllers/people_controller.rb
class PeopleController < ApplicationController
  def index
    @people = Tmdb::Person.popular(page: params[:page])
    @image = "http://image.tmdb.org/t/p/w185"
  end
  def show
    @person = Tmdb::Person.detail(params[:id])
    @image = "http://image.tmdb.org/t/p/w185"
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

  private

  def sign_up_params
    params.require(:user).permit(:username, :first_name, :last_name, :email, :password, :password_confirmation)
  end

  def account_update_params
    params.require(:user).permit(:username, :first_name, :last_name, :email, :password, :password_confirmation, :current_password)
  end
end

app/controllers/search_controller.rb
class SearchController < ApplicationController
  def index
      @q = params[:name]
      @tvsearch = Tmdb::Search.tv(@q)
      @personsearch = Tmdb::Search.person(@q)
      @moviesearch = Tmdb::Search.movie(@q)
  end
end

app/controllers/tv_controller.rb
class TvController < ApplicationController
  def index
    @tvshows = Tmdb::TV.popular(page: params[:page])
    @image = "https://image.tmdb.org/t/p/w500"

  end

  def show
    @tvshow = Tmdb::TV.detail(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/genres_helper.rb
module GenresHelper
end

app/helpers/movie_helper.rb
module MovieHelper
end

app/helpers/people_helper.rb
module PeopleHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/helpers/tv_helper.rb
module TvHelper
end

app/views/genres/index.html.erb
<h1 class= "text-center padding"> Search Movies By Genre </h1>
<div class = "row ">
<% @moviegenres.each do |m| %>
<div class = "col-6 text-center">
<%= link_to m.name, genre_path(m.id) %>
</div>
<% end %>
</div>

app/views/genres/show.html.erb
<h1 class= "text-center padding">
  <% @moviegenres.each do |m| %>
  <%  if m.id == @moviegenre.id %>
  <%= m.name %>
<% end %>
<% end %>
</h1>

<% @moviegenre.results.each do |m| %>
<p>
<%= link_to m.original_title, movie_path(m.id) %>
</p>
<% end %>

<div>
  <p class="left">
 <% if @moviegenre.page >= 2 %>
   <%= link_to "Previous Page", genre_path(:page => @moviegenre.page.to_i - 1 ) %>
 <% end %>
 </p>
  <p class="center">
   Currently on Page: <%= @moviegenre.page %> of 1000

 </p>
   <p class="right">
 <% if @moviegenre.page < 1000 %>
   <%= link_to "Next Page", genre_path(:page => @moviegenre.page.to_i + 1 ) %>
 <% end %>
 </p>

app/views/home/index.html.erb
<div class="jumbotron jumbotron-fluid">
  <div class="container">
  <h1 class="display-3">Hi <%= current_user.first_name %>!</h1>
  <h1 class="display-3">Welcome to ScreenTime!</h1>
  <p class="lead">ScreenTime is a movie database that allows you to look up information on tv, movies, and people.</p>
  <hr class="my-4">
  <div class = "row ">
  <p class="lead col-lg-4 col-md-4 col-sm-8">
    <%= link_to "Search Tv", tv_index_path, :class => "btn btn-primary btn-lg" %>
    </p>
      <p class="lead col-lg-4 col-md-4 col-sm-8">
    <%= link_to "Search Movies", movies_path, :class => "btn btn-primary btn-lg" %>
        </p>
      <p class="lead col-lg-4 col-md-4  col-sm-8">
    <%= link_to "Search People", people_path, :class => "btn btn-primary btn-lg" %>
        </p>
      </div>
    </div>
</div>

app/views/layouts/_header.html.erb
<%= react_component('NavBar', {}, { prerender: true}) %>

<div class = "float-right user-info">
<% if user_signed_in? %>
  Signed in as: <strong><%= current_user.username %></strong> |
  <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> - <%= link_to "Sign Out", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
<% else %>
  <%= link_to "Sign Up", new_user_registration_path, :class => 'navbar-link'  %> -
<%= link_to "Sign In", new_user_session_path, :class => 'navbar-link'  %>
<% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ScreenTime</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= favicon_link_tag asset_path('icon.png'), :rel => 'icon', :type =>  'image/png' %>
  </head>

  <body>
      <%=render :partial => "layouts/header" %>
      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>
      <div class="container">
        <%= yield %>
     </div>


  </body>
</html>

app/views/movie/index.html.erb
<h1 class= "text-center padding"> Popular Movies </h1>
<div class="results flex results_poster_card border border-primary">
  <% @movies.results.each do |m|  %>
    <div class="item poster card">
      <h3 class = "mx-auto d-block" > <%= link_to m.original_title, movie_path(m.id) %></h3>
      <div class="image_content ">
        <% if m.backdrop_path != nil %>
          <% image = @image + m.backdrop_path %>
          <%= image_tag(image, :class => "mx-auto d-block picture") %>
        <% end %>
      </div>
      <div class= "info">
          <div class = "overview">
          <p><%= m.overview %> </p>
          <p class="float">Rating: <%= m.vote_average %>/10.0</p>
          <p>Release Date: <%= m.release_date %></p>

            <p><%= link_to "More Info", movie_path(m.id) %></p>
          </div>

        </div>
    </div>
  <% end %>
</div>
 <div>
   <p class="left">
  <% if @movies.page >= 2 %>
    <%= link_to "Previous Page", movie_index_path(:page => @movies.page.to_i - 1 ) %>
  <% end %>
  </p>
   <p class="center">
    Currently on Page: <%= @movies.page %> of 1000

  </p>
    <p class="right">
  <% if @movies.page < 1000 %>
    <%= link_to "Next Page", movie_index_path(:page => @movies.page.to_i + 1 ) %>
  <% end %>
  </p>

</div>

app/views/movie/show.html.erb
<h3 class="text-center"><%= @movie.original_title %></h3>
<div class ="row">
  <div class = "col">
  <% if @movie.poster_path != nil %>
    <% image = @image + @movie.poster_path %>
    <%= image_tag(image) %>
  <% end %>
  </div>

  <div class="col pull-right">

      <p>Description: <%= @movie.overview %></p>

      <p> Genre(s): <% @movie.genres.each do |g| %>
            <%= g.name %>
    <% end %>
    </p>

    <p>Studio:
      <% @movie.production_companies.each do |q| %>
      <%= q.name %>
      <% end %>
    </p>

    <p> Relase date: <%= @movie.release_date %> </p>


    <p>Budget: <%= number_to_currency(@movie.budget) %> </p>
    <p>Revenue: <%= number_to_currency(@movie.revenue) %> </p>

    <p> More information:<%= link_to "IMBD Profile", "http://www.imdb.com/title/#{@movie.imdb_id}"%> </p>
    <p> Runtime: <%= @movie.runtime %> minutes </p>

    <p> Rating: <%= @movie.vote_average %>/10.0 </p>


    <% if @movie.homepage.present? %>
    <p> Homepage: <%= link_to @movie.homepage, @movie.homepage %>
    <% end %>


      <% if @movie.imdb_id.present? %>
    <p> <%= link_to "Click Here for IMDB Profile", "https/www.imdb.com/title/" + @movie.imdb_id %> </p>
        <% end %>
  </div>
</div>

app/views/movies/index.html.erb
<h1 class= "text-center padding"> Popular Movies </h1>
<div class="results flex results_poster_card border border-primary">
  <% @movies.results.each do |m|  %>
    <div class="item poster card">
      <h3 class = "mx-auto d-block" > <%= link_to m.original_title, movie_path(m.id) %></h3>
      <div class="image_content ">
        <% if m.backdrop_path != nil %>
          <% image = @image + m.backdrop_path %>
          <%= image_tag(image, :class => "mx-auto d-block picture") %>
        <% end %>
      </div>
      <div class= "info">
          <div class = "overview">
          <p><%= m.overview %> </p>
          <p class="float">Rating: <%= m.vote_average %>/10.0</p>
          <p>Release Date: <%= m.release_date %></p>

            <p><%= link_to "More Info", movie_path(m.id) %></p>
          </div>

        </div>
    </div>
  <% end %>
</div>
 <div>
   <p class="left">
  <% if @movies.page >= 2 %>
    <%= link_to "Previous Page", movies_path(:page => @movies.page.to_i - 1 ) %>
  <% end %>
  </p>
   <p class="center">
    Currently on Page: <%= @movies.page %> of 1000

  </p>
    <p class="right">
  <% if @movies.page < 1000 %>
    <%= link_to "Next Page", movies_path(:page => @movies.page.to_i + 1 ) %>
  <% end %>
  </p>

</div>

app/views/movies/show.html.erb
<h3 class="text-center"><%= @movie.original_title %></h3>
<div class ="row">
  <div class = "col">
  <% if @movie.poster_path != nil %>
    <% image = @image + @movie.poster_path %>
    <%= image_tag(image) %>
  <% end %>
  </div>

  <div class="col pull-right">

      <p>Description: <%= @movie.overview %></p>

      <p> Genre(s): <% @movie.genres.each do |g| %>
            <%= link_to g.name, genre_path(g.id) %>
    <% end %>
    </p>

    <p>Studio:
      <% @movie.production_companies.each do |q| %>
      <%= q.name %>
      <% end %>
    </p>

    <p> Relase date: <%= @movie.release_date %> </p>


    <p>Budget: <%= number_to_currency(@movie.budget) %> </p>
    <p>Revenue: <%= number_to_currency(@movie.revenue) %> </p>

    <p> Runtime: <%= @movie.runtime %> minutes </p>

    <p> Rating: <%= @movie.vote_average %>/10.0 </p>


    <% if @movie.homepage.present? %>
    <p> Homepage: <%= link_to @movie.homepage, @movie.homepage %>
    <% end %>


      <% if @movie.imdb_id.present? %>
    <p> <%= link_to "Click Here for IMDB Profile", "https/www.imdb.com/title/" + @movie.imdb_id %> </p>
        <% end %>
  </div>
</div>

app/views/people/index.html.erb
<h1 class= "text-center padding"> Popular People </h1>
<div class ="row">
  <% @people.results.each do |p| %>
  <div class= "col-3">

    <% if p.profile_path != nil %>
      <% image = @image + p.profile_path %>
      <%= image_tag(image, :class => "mx-auto d-block picture" ) %>
      <% end %>
    <h6 class="text-center"><%= link_to p.name, person_path(p.id) %></h6>
          </div>
  <% end %>
</div>

<div>
  <p class="left">
 <% if @people.page >= 2 %>
   <%= link_to "Previous Page", people_path(:page => @people.page.to_i - 1 ) %>
 <% end %>
 </p>
  <p class="center">
   Currently on Page: <%= @people.page %> of <%= @people.total_pages %>

 </p>
   <p class="right">
 <% if @people.page < 1000 %>
   <%= link_to "Next Page", people_path(:page => @people.page.to_i + 1 ) %>
 <% end %>
 </p>

</div>

app/views/people/show.html.erb
<h3 class="text-center padding"><%= @person.name %></h3>
<div class ="row">
  <div class="col-3">
    <% if @person.profile_path != nil %>
      <% image = @image + @person.profile_path %>
      <%= image_tag(image, :class => "mx-auto d-block picture") %>
    <% end %>
  </div>
  <div class ="col-9">

    <% if @person.biography != nil %>
      <p>Biography: <%= @person.biography %> </p>
    <% end %>

    <% if @person.birthday != nil %>
      <p>Born: <%= @person.birthday %> </p>
    <% end %>

    <% if @person.place_of_birth != nil %>
      <p>Place of Birth: <%= @person.place_of_birth %> </p>
    <% end %>


    <% if @person.gender != nil %>
      <p>Gender: <%= @person.gender == 2? "Male" : "Female" %></p>
    <% end %>

    <p>
      <% if @person.imdb_id != nil %>
      <%= link_to "Click here for IMBD Profile", "http://www.imdb.com/name/#{@person.imdb_id}"%>
      <% end %>
    </p>
    </div>
</div>

app/views/search/index.html.erb
<h1 class= "text-center padding"> Search Results </h1>
<div class="row">
<% if @tvsearch.total_results != 0 %>
<div class="col-sm-4">
<h3>TV Shows:</h3>
<%@tvsearch.results.each do |t| %>
<p>
<%= link_to t.name, tv_path(t.id) %>
</p>
<% end %>
<% end %>
</div>

<% if @moviesearch.total_results != 0 %>
<div class="col-sm-4">
<h3>Movie:</h3>
<% @moviesearch.results.each do |m| %>
<p>
<%= link_to m.original_title, movie_path(m.id) %>
</p>
<% end %>
</div>
<% end %>




<% if @personsearch.total_results != 0 %>
<div class="col-sm-4">
<h3>Person:</h3>
<% @personsearch.results.each do |p| %>
<p>
<%= link_to p.name, person_path(p.id) %>
</p>
<% end %>
</div>
<% end %>
</div>

app/views/tv/index.html.erb
<h1 class= "text-center padding"> Popular Tv Shows </h1>
<div class="results flex results_poster_card border border-primary">
  <% @tvshows.results.each do |m|  %>
    <div class="item poster card">
      <h4 class = "mx-auto d-block" > <%= link_to m.name, tv_path(m.id) %></h4>
      <div class="image_content ">
        <% if m.backdrop_path != nil %>
          <% image = @image + m.backdrop_path %>
          <%= image_tag(image, :class => "mx-auto d-block picture") %>
        <% end %>
      </div>
      <div class= "info">
          <div class = "overview"><%= m.overview %>
            <p>Rating: <%= m.vote_average %>/10.0</p>
            <p><%= link_to "More Info", tv_path(m.id) %></p>
          </div>

        </div>
    </div>
  <% end %>
</div>
 <div>
   <p class="left">
  <% if @tvshows.page >= 2 %>
    <%= link_to "Previous Page", tv_index_path(:page => @tvshows.page.to_i - 1 ) %>
  <% end %>
  </p>
   <p class="center">
    Currently on Page: <%= @tvshows.page %> of 1000

  </p>
    <p class="right">
  <% if @tvshows.page < 1000 %>
    <%= link_to "Next Page", tv_index_path(:page => @tvshows.page.to_i + 1 ) %>
  <% end %>
  </p>

</div>

app/views/tv/show.html.erb
  <h3 class="text-center"><%= @tvshow.name %></h3>

  <p> Genre(s): <% @tvshow.genres.each do |g| %>
          <%= g.name %>
  <% end %>
  </p>

  <p> Created by: <% @tvshow.created_by.each do |g| %>
          <%= g.name %>
  <% end %>
  </p>

  <p>Description: <%= @tvshow.overview %></p>

  <p>Number of Seasons: <%= @tvshow.number_of_seasons %></p>


  <p> Number of Episodes: <%= @tvshow.number_of_episodes %> </p>

  <p> Rating: <%= @tvshow.vote_average %>/10.0 </p>

  <p> First Air Date: <%= @tvshow.first_air_date%> </p>
  <p> Last Air Date: <%= @tvshow.last_air_date%> </p>
  <% if @tvshow.homepage.present? %>
  <p> Homepage: <%= link_to @tvshow.homepage, @tvshow.homepage %>
  <% end %>